### ISSUE TITLE
Deprecated: react-router-redux@5.0.0-alpha.9

### ISSUE THREAD

**Issue by neo** [Jam3/nyg-jam3#248]
We should not need this or we would need to find an alternative?

**Comment by DonghyukJacobJang** [comment]
#249

**Comment by namniak** [comment]
done

**Comment by neo** [comment]
I don't think it's resolved?
Also I think we could at least consider removing it as I'm not aware of many usage?

**Comment by neo** [comment]
actually it was just not published 😅  will create another discussion about removing it
